export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINES = "GET_MEDICINES"
export const DELETE_MEDICINES = "DELETE_MEDICINES"
export const ADD_MEDICINES = "ADD_MEDICINES"
export const UPDATE_MEDICINES = "UPDATE_MEDICINES"

export const GET_DEPARTMENT = "GET_DEPARTMENT"
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"
export const ADD_DEPARTMENT = "ADD_DEPARTMENT"
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT"